print ("Cual es tu nombre")
print ("Mi nombre es Ignacio")
print ("Cual es tu apellido?")
print ("Mi apellido es Pilar")
print ("De que seccion eres?")
print ("Soy de la seccion 752V")
print ("De que sede eres?")
print ("Soy de la sede Inacap Santiago Sur")
print ("Cual es tu nombre")
print ("Mi nombre es Samy")
print ("Cual es tu apellido?")
print ("Mi apellido es Miranda")
print ("De que seccion eres?")
print ("Soy de la seccion 752V")
print ("De que sede eres?")
print ("Soy de la sede Inacap Santiago Sur")
